version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tqs_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  spring-app:
    container_name: spring-app
    build:
      context: ./deticafe
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

  react-app:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  db_data:

