version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tqs_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - deticafe-network
  
  spring-app:
    container_name: spring-app
    build:
      context: ./deticafe
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tqs_project
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - deticafe-network

  react-app:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - deticafe-network

volumes:
    db_data:

networks:
  deticafe-network:
    driver: bridge





