package tqs_project.deticafe.Selenium;
// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.*;

class TestcreateOrderSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  void createOrderTest() {
    driver.get("http://localhost:5173/");
    driver.manage().window().setSize(new Dimension(1472, 774));
    vars.put("firstWindow", driver.getWindowHandle());
    vars.put("newWindow", driver.getWindowHandle());
    vars.put("win_ser_2", driver.getWindowHandle());
    driver.switchTo().window(vars.get("firstWindow").toString());
    String pageTitle = driver.getTitle();
    assertEquals("Deti cafe", pageTitle);
    driver.findElement(By.linkText("Drinks")).click();
    driver.findElement(By.cssSelector(".max-w-sm:nth-child(1) .mt-4")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".max-w-sm:nth-child(1) .mt-4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ml-2")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ml-2"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".bg-gray-200")).click();
    driver.findElement(By.linkText("Foods")).click();
    {
      WebElement element = driver.findElement(By.linkText("Foods"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".max-w-sm:nth-child(3) .mt-4")).click();
    driver.findElement(By.cssSelector(".flex:nth-child(2) > .mr-2")).click();
    driver.findElement(By.cssSelector(".bg-blue-500:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".bg-gray-200")).click();
    driver.findElement(By.cssSelector(".ml-2")).click();
    driver.findElement(By.cssSelector(".bg-blue-500")).click();
    driver.findElement(By.cssSelector(".bg-white:nth-child(1) > .w-full")).click();
    driver.switchTo().window(vars.get("newWindow").toString());
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".bg-gray-100"));
      assert (elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".bg-gray-100")).click();
    driver.switchTo().window(vars.get("win_ser_2").toString());
    driver.findElement(By.cssSelector(".mt-2")).click();
    driver.findElement(By.cssSelector(".flex > .bg-blue-500")).click();
  }
}