FROM maven:3.8.1-openjdk-17 AS build
# Set the working directory
WORKDIR /app

# Copy the application files
COPY . .

RUN mvn install -DskipTests

EXPOSE 8080

# Set the entry point
ENTRYPOINT ["mvn", "spring-boot:run"]