name: Deploy

on:
  push:
    branches:
      - main
      - TF-16-Set-Up-CD-Pipeline

  pull_request:
    branches:
      - main
      - TF-16-Set-Up-CD-Pipeline
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  acceptance_tests:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - uses: browser-actions/setup-firefox@latest
      - name: Setup DockerCompose for Integration Tests
        run: docker compose up -d
        working-directory: .

  build:
    needs: acceptance_tests
    name: Build
    runs-on: ubuntu-latest
    env:
      PRODUCTION: true
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v3
        with:
          push: true
          files: docker-compose.prod.yml
          workdir: .
          set: |
            *.cache-to=type=gha,scope=cached-stage,mode=max
            *.cache-from=type=gha,scope=cached-stage

  deploy:
    name: Deploy to UA VM
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Change permissions and ownership for files and directories
      run: |
        sudo find ~/actions-runner/_work/TQS_ProjetoFinal -type f -exec chmod 644 {} \;
        sudo find ~/actions-runner/_work/TQS_ProjetoFinal -type d -exec chmod 755 {} \;

    - name: Clean up old files
      run: |
        sudo rm -rf ~/actions-runner/_work/TQS_ProjetoFinal/TQS_ProjetoFinal

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy with docker-compose
      working-directory: .
      run: |
        docker compose -f docker-compose.prod.yml pull
        docker compose -f docker-compose.prod.yml up -d --remove-orphans
        docker container prune -f
        docker image prune -af
        docker builder prune
